---
sudo: false
language: ruby
cache: bundler
matrix:
  fast_finish: true
  include:
    - rvm: ruby-head
      gemfile: gemfiles/activerecord_edge.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/activerecord_edge.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/graphql_edge.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/activerecord_5.2.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/activerecord_4.2.gemfile
    - rvm: 2.3.0
      gemfile:  gemfiles/activerecord_4.2.gemfile
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/activerecord_edge.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/graphql_edge.gemfile
before_install:
  - gem update --system
  - gem install bundler -v 1.15.4
